server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservcies
    username: root
    password: nasir123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  https://dev-96844650.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaabvkfgtJVp2HYr5d7
            client-secret: ZNzxEWbyKpq7IHqllKJUljriGIXxzOB3PDnbDdWv

        provider:
          okta:
            issuer-uri:  https://dev-96844650.okta.com/oauth2/default


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        max-attempts: 6
        wait-duration: 3s
  ratelimiter:
    instances:
      ratingHotelFallBack:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s
okta:
  oauth2:
    issuer: https://dev-96844650.okta.com/oauth2/default
    audience: api://default


#      defaultZone: http://localhost:8761/eureka