server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8085


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: RATING-SERVCIE
          uri: lb://RATING-SERVCIE
          predicates:
            - Path=/ratings/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#okta configuration for api gateway
okta:
  oauth2:
    issuer: https://dev-96844650.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaabvkfgtJVp2HYr5d7
    client-secret: ZNzxEWbyKpq7IHqllKJUljriGIXxzOB3PDnbDdWv
    scopes: openid, profile, email, offline_access
